export const GET_USERS = "GET_USERS";

export const ADD_USERS = "ADD_USERS";

export const DELETE_USERS = "DELETE_USERS";

export const GET_SINGLE_USERS = "GET_SINGLE_USERS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
